### ISSUE TITLE
PRIVACY: Fingerprinting concerns

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/browser-extension#9]
If this injects to every page then this makes the end-user to be fingerprintable to gitpod crowd:

https://github.com/gitpod-io/browser-extension/blob/master/src/gitpodify.ts#L27

**Comment by corneliusludmann** [comment]
The current state in the master has never made it into the extension stores (due to to generous permission requests). The version 1.1 in the stores injects only in gitpod.io and github.com (thus it asks for the permissions to read these domains on installation). A PR with a new permission model in on the way (#12).

**Comment by Kreyren** [comment]
> The version 1.1 in the stores injects only in gitpod.io and github.com (thus it asks for the permissions to read these domains on installation).

Which makes it fingerprintable for gitpod.io and github.com to some extend.. Can't you run the extension based on website assuming that the cookie used for login is present?
